### ISSUE TITLE
End of life FOP Portal

### ISSUE THREAD

**Issue by sematuszewski** [faanskit/ha-esolar#15]
Do you plan to adapt the integration to the new EOP platform?

Unfortunately, the old FOP platform is scheduled to be deactivated after April 20.

I noticed that the new platform uses bearer tokens for login, which complicates simple login.
I analyzed the new platform for extracting historical data from voltage for SEC meter.
I managed to use Selenium for this purpose and I can extract data to json file, but it is historical data.

**Comment by faanskit** [comment]
I no longer own a SAJ inverter or hava an account, so sadly this repo will either die unless some takes over it.

**Comment by djansen1987** [comment]
If mine of this repository will not be maintained by new people (so far none for mine. I am advising to look into the following. 

https://github.com/wimb0/home-assistant-saj-r5-modbus

**Comment by walkjivefly** [comment]
I applied to SAJ for a developer account and got access to the new API details, but without an AppID and secretkey the information is useless. A week after applying for an AppID I'm still waiting and have heard nothing.

I'm exploring the DNS poisoning and MQTT interception route instead.

**Comment by sematuszewski** [comment]
> I applied to SAJ for a developer account and got access to the new API details, but without an AppID and secretkey the information is useless. A week after applying for an AppID I'm still waiting and have heard nothing.
> 
> I'm exploring the DNS poisoning and MQTT interception route instead.

Great news :)
Can you tell me where exactly you applied for access to the developer account?

I have quite good contact with support in Poland and it is possible that if I also applied for a developer account they would give me login details faster :)

**Comment by walkjivefly** [comment]
You can log in to the following website and register an account for further assistance:
https://developer.saj-electric.com/fileCenter/index

After registering an account the API doc is visible. You're then supposed to apply for an AppID and secret key. They say that takes 1 business day. That's not been my experience.....

**Comment by genicus** [comment]
@walkjivefly, what kind of inverter do you have? Have you been able to get somewhere with MQTT? My inverter is sending data to my own MQTT server now, but nothing obvious comes out of it unfortunately. I found the project by paolosabatino. This is for an H1 and unfortunately does not work for my R5...

**Comment by walkjivefly** [comment]
> [@walkjivefly](https://github.com/walkjivefly), what kind of inverter do you have? Have you been able to get somewhere with MQTT? My inverter is sending data to my own MQTT server now, but nothing obvious comes out of it unfortunately. I found the project by paolosabatino. This is for an H1 and unfortunately does not work for my R5...

Yes, I'm getting data fine from an H1 3.6k using https://github.com/h3llrais3r/ha-saj-h1-mqtt which is a slightly updated version of the paolosabatini integration. It was a bit of a learning curve. There's more information about what I needed to do in https://github.com/paolosabatino/saj-mqtt-ha/discussions/4 

I've still not had a reply to the application for an AppID and secretkey so I've given up on that approach. 

Sorry to hear the MQTT integration doesn't work for an H5. I don't understand anywhere near enough about how it works to offer any helpful suggestions. In the discussion liked above is a link to a Telegram group which AFAIK is where the information about the SAJ MQTT protocol came from. There might be information in there about the H5.

**Comment by sematuszewski** [comment]
Hello,

Is there anyone here besides me who still has the SAJ SEC module?

Currently, I am able to log into the new portal using a Selenium script and extract data in json from the portal sent by the SEC module.



Endpoint, which returns data in json after logging for the SEC module (endpoint is responsible for displaying historical data, but you can limit the query to the last updated value in the data)


https://eop.saj-electric.com/dev-api/api/v1/monitor/sec/getSECHistoryDataList?pageNo=1&pageSize=**1**&plantUid=**YOUR_PLANT_UID**&moduleSn=YOUR_SEC_MODULE_SN&chartDateType=1&chartDay=**YYYY-MM-DD**&appProjectName=elekeeper&clientDate=2025-04-21&lang=en&timeStamp=1745271622417&random=nn783v3WvsweM5PryFHatXKGkdhhhjw5&clientId=esolar-monitor-admin&signParams=pageNo,pageSize,plantUid,moduleSn,chartDateType,chartDay,appProjectName,clientDate,lang,timeStamp,random,clientId&signature=GA3F1BE42122FDB47BF941B6B4B881C5ACD04C767


pageSize - from 1 (last updated data from a specific date) to 1000 (all data from a specific date in a single json response, but the sec module sends data on average every 5 minutes [24*60/5=288 average updates per day], so in general, anything above 300 will pull all updates).

plantUid - unique plantUid

moduleSn - sec module serial number

chartDay - date in YYYY-MM-DD format, example: 2025-01-01 retrieves data from the first day of January 2025.

All other parameters are currently irrelevant, some take random values, I don't know yet what they are generated from, but in general tests have shown that specifying anything in them causes no change.

RAW JSON:

```
{"data":{"endRow":0,"hasNextPage":false,"hasPreviousPage":false,"isFirstPage":true,"isLastPage":true,"list":[{"dataTime":"2025-04-21 23:59:18","moduleLink":"wifi","moduleSignal":-82,"moduleSn":"SEC_SERIAL_NUMBER","monthExportEnergy":0,"monthImportEnergy":0,"monthLoadEnergy":0,"monthPvgenConsumptEnergy":0,"monthPvgenEnergy":0,"phase1ExportEnergy":0,"phase1GridCurr":0.15,"phase1GridFreq":49.99,"phase1GridPower":4,"phase1GridPowerfactor":0.121,"phase1GridVolt":222.10,"phase1ImportEnergy":0,"phase1LoadCurr":0.15,"phase1LoadFreq":49.99,"phase1LoadPower":4,"phase1LoadPowerfactor":0.000,"phase1LoadVolt":222.10,"phase1PvgenCurr":0.00,"phase1PvgenFreq":0,"phase1PvgenPower":0,"phase1PvgenPowerfactor":0.000,"phase1PvgenVolt":0.00,"phase2ExportEnergy":0,"phase2GridCurr":0.21,"phase2GridFreq":49.99,"phase2GridPower":8,"phase2GridPowerfactor":0.178,"phase2GridVolt":221.90,"phase2ImportEnergy":0,"phase2LoadCurr":0.21,"phase2LoadFreq":49.99,"phase2LoadPower":8,"phase2LoadPowerfactor":0.000,"phase2LoadVolt":221.90,"phase2PvgenCurr":0.00,"phase2PvgenFreq":0.00,"phase2PvgenPower":0,"phase2PvgenPowerfactor":0.000,"phase2PvgenVolt":0.00,"phase3ExportEnergy":0,"phase3GridCurr":1.25,"phase3GridFreq":49.99,"phase3GridPower":180,"phase3GridPowerfactor":0.630,"phase3GridVolt":225.20,"phase3ImportEnergy":0,"phase3LoadCurr":1.25,"phase3LoadFreq":49.99,"phase3LoadPower":180,"phase3LoadPowerfactor":0.000,"phase3LoadVolt":225.20,"phase3PvgenCurr":0.00,"phase3PvgenFreq":0.00,"phase3PvgenPower":0,"phase3PvgenPowerfactor":0.000,"phase3PvgenVolt":0.00,"todayExportEnergy":18.29,"todayImportEnergy":2.10,"todayLoadEnergy":3.76,"todayPvgenConsumptEnergy":1.66,"todayPvgenEnergy":19.95,"totalExportEnergy":9838.11,"totalGridPower":192,"totalGridPowerfactor":0.000,"totalGridQpower":-259,"totalImportEnergy":5730.11,"totalLoadEnergy":11431.91,"totalLoadPower":192,"totalLoadPowerfactor":0.000,"totalLoadQpower":0,"totalPvgenConsumpEnergy":5701.80,"totalPvgenEnergy":15539.91,"totalPvgenPower":0,"totalPvgenPowerfactor":0.000,"totalPvgenQpower":0,"yearExportEnergy":0,"yearImportEnergy":0,"yearLoadEnergy":0,"yearPvgenConsumptEnergy":0,"yearPvgenEnergy":0}],"navigateFirstPage":1,"navigateLastPage":1,"navigatePages":8,"navigatepageNums":[1],"nextPage":0,"pageNum":1,"pageSize":1,"pages":1,"prePage":0,"size":1,"startRow":0,"total":294},"errCode":0,"errMsg":"0"}
```



CONVERTED TO YAML:

```
data:
  endRow: 0
  hasNextPage: false
  hasPreviousPage: false
  isFirstPage: true
  isLastPage: true
  list:
    - dataTime: '2025-04-21 23:59:18'
      moduleLink: wifi
      moduleSignal: -82
      moduleSn: SEC_SERIAL_NUMBER
      monthExportEnergy: 0
      monthImportEnergy: 0
      monthLoadEnergy: 0
      monthPvgenConsumptEnergy: 0
      monthPvgenEnergy: 0
      phase1ExportEnergy: 0
      phase1GridCurr: 0.15
      phase1GridFreq: 49.99
      phase1GridPower: 4
      phase1GridPowerfactor: 0.121
      phase1GridVolt: 222.1
      phase1ImportEnergy: 0
      phase1LoadCurr: 0.15
      phase1LoadFreq: 49.99
      phase1LoadPower: 4
      phase1LoadPowerfactor: 0
      phase1LoadVolt: 222.1
      phase1PvgenCurr: 0
      phase1PvgenFreq: 0
      phase1PvgenPower: 0
      phase1PvgenPowerfactor: 0
      phase1PvgenVolt: 0
      phase2ExportEnergy: 0
      phase2GridCurr: 0.21
      phase2GridFreq: 49.99
      phase2GridPower: 8
      phase2GridPowerfactor: 0.178
      phase2GridVolt: 221.9
      phase2ImportEnergy: 0
      phase2LoadCurr: 0.21
      phase2LoadFreq: 49.99
      phase2LoadPower: 8
      phase2LoadPowerfactor: 0
      phase2LoadVolt: 221.9
      phase2PvgenCurr: 0
      phase2PvgenFreq: 0
      phase2PvgenPower: 0
      phase2PvgenPowerfactor: 0
      phase2PvgenVolt: 0
      phase3ExportEnergy: 0
      phase3GridCurr: 1.25
      phase3GridFreq: 49.99
      phase3GridPower: 180
      phase3GridPowerfactor: 0.63
      phase3GridVolt: 225.2
      phase3ImportEnergy: 0
      phase3LoadCurr: 1.25
      phase3LoadFreq: 49.99
      phase3LoadPower: 180
      phase3LoadPowerfactor: 0
      phase3LoadVolt: 225.2
      phase3PvgenCurr: 0
      phase3PvgenFreq: 0
      phase3PvgenPower: 0
      phase3PvgenPowerfactor: 0
      phase3PvgenVolt: 0
      todayExportEnergy: 18.29
      todayImportEnergy: 2.1
      todayLoadEnergy: 3.76
      todayPvgenConsumptEnergy: 1.66
      todayPvgenEnergy: 19.95
      totalExportEnergy: 9838.11
      totalGridPower: 192
      totalGridPowerfactor: 0
      totalGridQpower: -259
      totalImportEnergy: 5730.11
      totalLoadEnergy: 11431.91
      totalLoadPower: 192
      totalLoadPowerfactor: 0
      totalLoadQpower: 0
      totalPvgenConsumpEnergy: 5701.8
      totalPvgenEnergy: 15539.91
      totalPvgenPower: 0
      totalPvgenPowerfactor: 0
      totalPvgenQpower: 0
      yearExportEnergy: 0
      yearImportEnergy: 0
      yearLoadEnergy: 0
      yearPvgenConsumptEnergy: 0
      yearPvgenEnergy: 0
  navigateFirstPage: 1
  navigateLastPage: 1
  navigatePages: 8
  navigatepageNums:
    - 1
  nextPage: 0
  pageNum: 1
  pageSize: 1
  pages: 1
  prePage: 0
  size: 1
  startRow: 0
  total: 294
errCode: 0
errMsg: '0'
```

I can upload my test scripts to git if anyone would like to help customize them for use in HA.
I just want to say that they were written to simply work, they are not written to be “pretty” ;)
